name: Deploy to Cloud Run

on:
  push:
    branches:
      - main # ou master, dependendo do nome da tua branch principal

env:
  PROJECT_ID: sisrua-producao
  REGION: southamerica-east1
  SERVICE_NAME: sisrua-app

jobs:
  deploy:
    runs-on: ubuntu-latest

    # Permissões estritas necessárias para o Workload Identity funcionar (OIDC)
    permissions:
      contents: 'read'
      id-token: 'write'

    steps:
      - name: Checkout do código
        uses: actions/checkout@v4

      - name: Autenticação no Google Cloud
        id: auth
        uses: google-github-actions/auth@v2
        with:
          workload_identity_provider: 'projects/244319582382/locations/global/workloadIdentityPools/github-pool/providers/github-provider'
          service_account: '244319582382-compute@developer.gserviceaccount.com'

      - name: Configurar o Google Cloud SDK
        uses: google-github-actions/setup-gcloud@v2

      - name: Deploy no Cloud Run
        run: |
          gcloud run deploy ${{ env.SERVICE_NAME }} \
            --source . \
            --region ${{ env.REGION }} \
            --allow-unauthenticated \
            --memory 1024Mi \
            --set-env-vars="GROQ_API_KEY=${{ secrets.GROQ_API_KEY }},GCP_PROJECT=sisrua-producao,CLOUD_TASKS_LOCATION=southamerica-east1,CLOUD_TASKS_QUEUE=sisrua-queue,CLOUD_RUN_BASE_URL=https://sisrua-app-244319582382.southamerica-east1.run.app"